"""Build a self-contained HTML dashboard from the processed data.

Reads whatever exists under ``data/processed`` and the latest raw snapshot, and
writes ``data/processed/dashboard.html`` — a single file you can open in a
browser or publish. Regenerated by ``cli.py dashboard`` and at the end of
``cli.py all``.
"""
from __future__ import annotations

import json
from datetime import date, datetime, timezone

import numpy as np
import pandas as pd

from .areas import area_short
from .config import Config

CORE_OUTCODES = [f"EH{i}" for i in range(1, 18)]
BED_ORDER = ["Studio", "1", "2", "3", "4", "5", "6+"]
AREA_MIN_LISTINGS = 8  # ignore very thin districts in the area views


# --------------------------------------------------------------------------- #
# Payload
# --------------------------------------------------------------------------- #
def _latest_raw(cfg: Config) -> pd.DataFrame:
    files = sorted(cfg.raw_rightmove_dir.glob(f"{cfg.rightmove.location_slug}_*.parquet"))
    if not files:
        return pd.DataFrame()
    df = pd.read_parquet(files[-1])
    df = df[df["price"].notna() & (df["price"] > 0)].copy()
    df["first_visible_date"] = pd.to_datetime(
        df["first_visible_date"], errors="coerce", utc=True
    )
    return df


def _bed_bucket(n) -> str | None:
    if pd.isna(n):
        return None
    n = int(n)
    if n <= 0:
        return "Studio"
    if n >= 6:
        return "6+"
    return str(n)


def _histogram(prices: pd.Series) -> dict:
    if prices.empty:
        return {"edges": [], "counts": []}
    cap = float(min(prices.quantile(0.98), 1_500_000))
    edges = list(np.arange(0, cap + 50_000, 50_000))
    counts, _ = np.histogram(prices.clip(upper=cap), bins=edges)
    return {"edges": [int(e) for e in edges], "counts": [int(c) for c in counts]}


def build_payload(cfg: Config) -> dict:
    P = cfg.processed_dir
    raw = _latest_raw(cfg)

    payload: dict = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "location": cfg.rightmove.location_name,
    }

    # --- latest Rightmove snapshot ------------------------------------------
    if not raw.empty:
        snap_day = str(raw["snapshot_date"].iloc[0])
        price = raw["price"]
        dom = (pd.Timestamp(snap_day, tz="UTC") - raw["first_visible_date"]).dt.days
        payload["snapshot"] = {
            "date": snap_day,
            "n_listings": int(len(raw)),
            "median_price": float(price.median()),
            "mean_price": float(price.mean()),
            "p25_price": float(price.quantile(0.25)),
            "p75_price": float(price.quantile(0.75)),
            "pct_reduced": float(100 * (raw["added_or_reduced_kind"] == "Reduced").mean()),
            "n_new_7d": int((dom <= 7).sum()),
            "n_new_30d": int((dom <= 30).sum()),
            "median_days_on_market": float(dom.median()) if dom.notna().any() else None,
        }
        city_median = float(price.median())
        by_area = []
        for oc in CORE_OUTCODES:
            sub = raw.loc[raw["outcode"] == oc, "price"]
            if len(sub) < 3:
                continue
            reduced = raw.loc[raw["outcode"] == oc, "added_or_reduced_kind"]
            dom_oc = dom[raw["outcode"] == oc]
            by_area.append({
                "seg": oc,
                "name": area_short(oc),
                "n": int(len(sub)),
                "median": float(sub.median()),
                "p25": float(sub.quantile(0.25)),
                "p75": float(sub.quantile(0.75)),
                "vs_city": float(sub.median() / city_median - 1),
                "pct_reduced": float(100 * (reduced == "Reduced").mean()),
                "median_dom": float(dom_oc.median()) if dom_oc.notna().any() else None,
            })
        by_area.sort(key=lambda r: r["median"])
        payload["by_outcode"] = [
            {"seg": r["seg"], "n": r["n"], "median": r["median"]} for r in by_area
        ]
        payload["by_area"] = by_area
        payload["city_median"] = city_median
        by_type = (
            raw.groupby("property_sub_type")["price"]
            .agg(["size", "median"]).reset_index()
            .sort_values("size", ascending=False).head(9)
        )
        payload["by_type"] = [
            {"seg": r["property_sub_type"], "n": int(r["size"]), "median": float(r["median"])}
            for _, r in by_type.iterrows()
        ]
        raw["_bed"] = raw["bedrooms"].map(_bed_bucket)
        by_bed = raw.dropna(subset=["_bed"]).groupby("_bed")["price"].agg(["size", "median"])
        payload["by_bedrooms"] = [
            {"seg": b, "n": int(by_bed.loc[b, "size"]), "median": float(by_bed.loc[b, "median"])}
            for b in BED_ORDER if b in by_bed.index
        ]
        qual = raw["price_qualifier"].fillna("Not specified").value_counts().head(7)
        payload["price_qualifier"] = [
            {"seg": k, "n": int(v)} for k, v in qual.items()
        ]
        payload["price_distribution"] = _histogram(price)

    # --- Rightmove series over time --------------------------------------
    ts_path = P / "market_timeseries.csv"
    if ts_path.exists():
        ts = pd.read_csv(ts_path)
        payload["asking_over_time"] = [
            {"t": r["snapshot_date"], "median": _f(r["median_price"]),
             "p25": _f(r["p25_price"]), "p75": _f(r["p75_price"]), "n": int(r["n_listings"])}
            for _, r in ts.iterrows()
        ]
        payload["inventory_over_time"] = [
            {"t": r["snapshot_date"], "n_listings": int(r["n_listings"]),
             "pct_reduced": _f(r["pct_reduced"]), "median_dom": _f(r["median_days_on_market"])}
            for _, r in ts.iterrows()
        ]

    # --- median asking price by area, over time -------------------------
    seg_path = P / "market_timeseries_by_segment.csv"
    if seg_path.exists():
        seg = pd.read_csv(seg_path)
        seg = seg[seg["segment_kind"] == "outcode"].copy()
        if not seg.empty:
            dates = sorted(seg["snapshot_date"].unique())
            latest = dates[-1]
            keep = set(
                seg.loc[(seg["snapshot_date"] == latest) & (seg["n_listings"] >= AREA_MIN_LISTINGS),
                        "segment"]
            )
            series, movers = [], []
            for oc in sorted(keep, key=lambda o: int(o[2:])):
                rows = seg[seg["segment"] == oc].set_index("snapshot_date")
                pts = [_f(rows["median_price"].get(d)) for d in dates]
                series.append({"seg": oc, "name": area_short(oc), "points": pts})
                have = [(d, rows["median_price"].get(d)) for d in dates
                        if pd.notna(rows["median_price"].get(d))]
                if len(have) >= 2:
                    first_p, last_p = have[0][1], have[-1][1]
                    movers.append({
                        "seg": oc, "name": area_short(oc),
                        "first": float(first_p), "last": float(last_p),
                        "abs": float(last_p - first_p),
                        "pct": float(100 * (last_p / first_p - 1)),
                        "from": have[0][0], "to": have[-1][0],
                    })
            movers.sort(key=lambda r: r["pct"], reverse=True)
            payload["area_trend"] = {"dates": list(dates), "series": series}
            payload["area_movers"] = movers

    # --- UK HPI + forecast ------------------------------------------------
    hpi_path = cfg.raw_ukhpi_dir / f"ukhpi_{cfg.ukhpi.region_slug}.csv"
    if hpi_path.exists():
        hpi = pd.read_csv(hpi_path).dropna(subset=["averagePrice"])
        latest = hpi.iloc[-1]
        payload["ukhpi"] = {
            "latest_month": str(latest["month"]),
            "avg_price": float(latest["averagePrice"]),
            "annual_change_pct": _f(latest["percentageAnnualChange"]),
            "index": _f(latest["housePriceIndex"]),
            "history": [
                {"t": r["month"], "price": float(r["averagePrice"])}
                for _, r in hpi.iterrows()
            ],
        }

    fc_path = P / "forecast_ukhpi.csv"
    if fc_path.exists():
        fc = pd.read_csv(fc_path)
        act = fc[fc["kind"] == "actual"]
        fut = fc[fc["kind"] == "forecast"]
        if not fut.empty:
            last_actual = float(act["avg_price"].iloc[-1])
            proj = float(fut["avg_price"].iloc[-1])
            payload["forecast"] = {
                "horizon_months": int(len(fut)),
                "last_actual_price": last_actual,
                "last_actual_month": str(pd.to_datetime(act["date"].iloc[-1]).date()),
                "projected_price": proj,
                "projected_month": str(pd.to_datetime(fut["date"].iloc[-1]).date()),
                "projected_change_pct": 100 * (proj / last_actual - 1),
                "lo95": float(fut["lo95"].iloc[-1]),
                "hi95": float(fut["hi95"].iloc[-1]),
                "actual": [
                    {"t": str(pd.to_datetime(r["date"]).date()), "price": float(r["avg_price"])}
                    for _, r in act.tail(120).iterrows()
                ],
                "forecast": [
                    {"t": str(pd.to_datetime(r["date"]).date()), "price": float(r["avg_price"]),
                     "lo80": _f(r["lo80"]), "hi80": _f(r["hi80"]),
                     "lo95": _f(r["lo95"]), "hi95": _f(r["hi95"])}
                    for _, r in fut.iterrows()
                ],
            }

    # --- run history ----------------------------------------------------
    idx_path = P / "snapshot_index.csv"
    if idx_path.exists():
        payload["n_snapshots"] = int(len(pd.read_csv(idx_path)))

    return payload


def _f(v):
    return None if pd.isna(v) else float(v)


# --------------------------------------------------------------------------- #
# Render
# --------------------------------------------------------------------------- #
def render_html(payload: dict, *, standalone: bool = True) -> str:
    data_json = json.dumps(payload, allow_nan=False)
    content = _TEMPLATE.replace("__DATA__", data_json)
    if not standalone:
        return content
    return (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "<style>body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>\n"
        "</head>\n<body>\n" + content + "\n</body>\n</html>\n"
    )


def build_dashboard(cfg: Config) -> dict:
    cfg.ensure_dirs()
    payload = build_payload(cfg)
    out = cfg.processed_dir / "dashboard.html"
    out.write_text(render_html(payload, standalone=True), encoding="utf-8")
    # Body-only fragment, handy for publishing as an Artifact.
    (cfg.processed_dir / "dashboard.fragment.html").write_text(
        render_html(payload, standalone=False), encoding="utf-8"
    )
    snap = payload.get("snapshot", {})
    print(f"  dashboard -> {out}")
    if snap:
        print(
            f"  {snap['date']}: {snap['n_listings']} listings, median asking "
            f"£{snap['median_price']:,.0f}, {snap['pct_reduced']:.0f}% reduced"
        )
    return payload


# --------------------------------------------------------------------------- #
# Template  (title + styles + markup + inline chart script)
# --------------------------------------------------------------------------- #
_TEMPLATE = r"""
<title>Edinburgh Housing Monitor</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<style>
  :root{
    --page:#f4f5f7; --surface:#ffffff; --surface-2:#fafbfc;
    --ink:#14161a; --ink-2:#565b62; --muted:#878b91;
    --grid:#e6e8eb; --hair:rgba(20,22,26,.10);
    --accent:#2a78d6; --accent-soft:rgba(42,120,214,.12);
    --orange:#eb6834; --aqua:#1baf7a; --warn:#c98500; --down:#b23b2e; --up:#006300;
    --c1:#2a78d6; --c2:#eb6834; --c3:#1baf7a; --c4:#eda100; --c5:#e87ba4; --c6:#4a3aa7;
    --radius:10px;
    --sans:"IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif;
    --mono:"IBM Plex Mono",ui-monospace,"SF Mono",Menlo,Consolas,monospace;
  }
  @media (prefers-color-scheme:dark){
    :root:not([data-theme="light"]){
      --page:#0e0e10; --surface:#1a1a1c; --surface-2:#202024;
      --ink:#f3f4f6; --ink-2:#b9bcc2; --muted:#8a8e95;
      --grid:#2a2b2e; --hair:rgba(255,255,255,.12);
      --accent:#3987e5; --accent-soft:rgba(57,135,229,.16);
      --orange:#d95926; --aqua:#199e70; --warn:#e0a838; --down:#e8705d; --up:#4fb04f;
      --c1:#3987e5; --c2:#d95926; --c3:#199e70; --c4:#c98500; --c5:#d55181; --c6:#9085e9;
    }
  }
  :root[data-theme="dark"]{
    --page:#0e0e10; --surface:#1a1a1c; --surface-2:#202024;
    --ink:#f3f4f6; --ink-2:#b9bcc2; --muted:#8a8e95;
    --grid:#2a2b2e; --hair:rgba(255,255,255,.12);
    --accent:#3987e5; --accent-soft:rgba(57,135,229,.16);
    --orange:#d95926; --aqua:#199e70; --warn:#e0a838; --down:#e8705d; --up:#4fb04f;
    --c1:#3987e5; --c2:#d95926; --c3:#199e70; --c4:#c98500; --c5:#d55181; --c6:#9085e9;
  }

  *{box-sizing:border-box}
  body{margin:0;background:var(--page);color:var(--ink);font-family:var(--sans);
    -webkit-font-smoothing:antialiased;line-height:1.5}
  .wrap{max-width:1080px;margin:0 auto;padding:40px 24px 72px}

  header{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px 16px;
    padding-bottom:20px;border-bottom:1px solid var(--hair);margin-bottom:28px}
  h1{font-size:23px;font-weight:700;letter-spacing:-.01em;margin:0}
  .sub{color:var(--ink-2);font-size:13px}
  .sub .mono{font-family:var(--mono);color:var(--ink)}

  h2{font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.09em;
    color:var(--muted);margin:36px 0 14px}
  h2:first-of-type{margin-top:8px}

  .kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;
    background:var(--hair);border:1px solid var(--hair);border-radius:var(--radius);overflow:hidden}
  @media (max-width:860px){.kpis{grid-template-columns:repeat(3,1fr)}}
  @media (max-width:480px){.kpis{grid-template-columns:repeat(2,1fr)}}
  .kpi{background:var(--surface);padding:15px 16px 14px}
  .kpi .k{font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}
  .kpi .v{font-family:var(--mono);font-size:21px;font-weight:600;margin-top:6px;letter-spacing:-.01em}
  .kpi .d{font-size:11.5px;color:var(--ink-2);margin-top:3px}
  .kpi .d.down{color:var(--down)} .kpi .d.up{color:var(--up)}

  .card{background:var(--surface);border:1px solid var(--hair);border-radius:var(--radius);
    padding:18px 18px 14px}
  .card .ct{font-size:13.5px;font-weight:600;margin:0 0 2px}
  .card .cs{font-size:12px;color:var(--ink-2);margin:0 0 12px}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  .grid3{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  @media (max-width:720px){.grid2,.grid3{grid-template-columns:1fr}}

  .chartbox{position:relative;width:100%}
  .h-hero{height:340px} .h-med{height:240px} .h-tall{height:300px}

  .note{font-size:12px;color:var(--muted);font-style:italic;margin-top:10px}
  .empty{display:flex;align-items:center;justify-content:center;height:100%;
    color:var(--muted);font-size:12.5px;text-align:center;padding:0 24px}

  .lt{width:100%;border-collapse:collapse;font-size:12.5px}
  .lt th{text-align:right;font-weight:600;color:var(--muted);font-size:10.5px;
    text-transform:uppercase;letter-spacing:.06em;padding:0 10px 8px;border-bottom:1px solid var(--hair)}
  .lt th:first-child,.lt td:first-child{text-align:left}
  .lt td{padding:8px 10px;border-bottom:1px solid var(--hair);
    font-family:var(--mono);font-variant-numeric:tabular-nums;color:var(--ink-2)}
  .lt td:first-child{font-family:var(--sans);color:var(--ink)}
  .lt tr:last-child td{border-bottom:0}
  .lt .pos{color:var(--up)} .lt .neg{color:var(--down)}
  .lt .oc{color:var(--muted);font-family:var(--mono);font-size:11px}
  .scroller{overflow-x:auto}

  footer{margin-top:44px;padding-top:18px;border-top:1px solid var(--hair);
    font-size:12px;color:var(--muted)}
  footer b{color:var(--ink-2);font-weight:600}
  a{color:var(--accent)}
</style>

<div class="wrap">
  <header>
    <h1>Edinburgh Housing Monitor</h1>
    <span class="sub">Rightmove asking prices &amp; stock vs the official UK House Price Index &nbsp;·&nbsp;
      generated <span class="mono" id="gen"></span></span>
  </header>

  <h2>Where the market is now</h2>
  <div class="kpis" id="kpis"></div>

  <h2>Sold-price benchmark &amp; forecast</h2>
  <div class="card">
    <p class="ct">City of Edinburgh average sold price — UK HPI, with 12-month projection</p>
    <p class="cs" id="fc-cs">Seasonal ARIMA on the UK House Price Index (incorporates Registers of Scotland). Shaded band = 95% interval.</p>
    <div class="chartbox h-hero"><canvas id="c-forecast"></canvas></div>
    <p class="note" id="fc-note"></p>
  </div>

  <h2>Cheaper vs dearer — Edinburgh by area</h2>
  <div class="grid2">
    <div class="card">
      <p class="ct">Median asking price by area</p>
      <p class="cs">Postcode districts, cheapest to dearest. Dashed line = city median. Numbers after each bar are listing counts.</p>
      <div class="chartbox h-tall"><canvas id="c-area-rank"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">How the spread is trending</p>
      <p class="cs" id="area-trend-cs">Median asking price per snapshot for the three cheapest and three dearest areas.</p>
      <div class="chartbox h-tall"><canvas id="c-area-trend"></canvas></div>
    </div>
  </div>
  <div class="card" style="margin-top:16px">
    <p class="ct">Area league table</p>
    <p class="cs" id="area-table-cs">Every district with 8+ listings today, cheapest first. &ldquo;vs city&rdquo; compares the area median to the whole-city median.</p>
    <div class="scroller"><table class="lt" id="area-table"></table></div>
  </div>

  <h2>Rightmove asking prices &amp; stock over time</h2>
  <div class="grid2">
    <div class="card">
      <p class="ct">Median asking price</p>
      <p class="cs">Interquartile range shaded. One point per daily snapshot.</p>
      <div class="chartbox h-med"><canvas id="c-asking"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">Live listings on the market</p>
      <p class="cs">Total stock per snapshot. Hover for the share showing a price cut.</p>
      <div class="chartbox h-med"><canvas id="c-inventory"></canvas></div>
    </div>
  </div>
  <p class="note" id="ts-note"></p>

  <h2>Today's stock, broken down</h2>
  <div class="grid2">
    <div class="card">
      <p class="ct">Median asking price by property type</p>
      <p class="cs">Most common types in the current snapshot.</p>
      <div class="chartbox h-tall"><canvas id="c-type"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">Median asking price by bedroom count</p>
      <p class="cs">Bars labelled with listing counts. 0-bed = parking, land and studios.</p>
      <div class="chartbox h-tall"><canvas id="c-beds"></canvas></div>
    </div>
  </div>
  <div class="grid2" style="margin-top:16px">
    <div class="card">
      <p class="ct">Asking price distribution</p>
      <p class="cs">All priced listings, £50k bins, top 2% clipped.</p>
      <div class="chartbox h-med"><canvas id="c-dist"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">How prices are quoted</p>
      <p class="cs">Mostly <em>Offers Over</em> — the asking figure is a floor, and the sale usually closes above it.</p>
      <div class="chartbox h-med"><canvas id="c-qual"></canvas></div>
    </div>
  </div>

  <footer>
    <p><b>Reading this.</b> The UK HPI is the lagging ground truth (actual sold prices, ~2 months behind).
    The Rightmove series leads it — asking prices, stock and discounting turn first. The forecast currently
    uses UK HPI history only; Rightmove momentum joins as an input once several months of snapshots accrue.</p>
    <p style="margin-top:8px"><b>Sources.</b> Rightmove for-sale listings for <span id="loc"></span> (personal research, one sweep per day).
    UK House Price Index, HM Land Registry / Registers of Scotland, City of Edinburgh series.
    Snapshots to date: <span id="nsnap">1</span>.</p>
  </footer>
</div>

<script>
const DATA = __DATA__;
const $ = s => document.querySelector(s);

const gbp0 = n => "£" + Math.round(n).toLocaleString("en-GB");
const gbpK = n => n >= 1e6 ? "£" + (n/1e6).toFixed(2) + "m" : "£" + Math.round(n/1e3) + "k";
const pct1 = n => (n>0?"+":"") + n.toFixed(1) + "%";

function tok(name){ return getComputedStyle(document.documentElement).getPropertyValue(name).trim(); }
function palette(){
  return {
    ink: tok("--ink"), ink2: tok("--ink-2"), muted: tok("--muted"),
    grid: tok("--grid"), surface: tok("--surface"),
    accent: tok("--accent"), accentSoft: tok("--accent-soft"),
    orange: tok("--orange"), aqua: tok("--aqua"), warn: tok("--warn"),
    down: tok("--down"), up: tok("--up"),
    cat: [tok("--c1"), tok("--c2"), tok("--c3"), tok("--c4"), tok("--c5"), tok("--c6")],
  };
}

let CHARTS = [];
function destroyAll(){ CHARTS.forEach(c => c.destroy()); CHARTS = []; }

function baseOpts(p){
  return {
    responsive:true, maintainAspectRatio:false, animation:false,
    interaction:{ mode:"index", intersect:false },
    layout:{ padding:{ top:6, right:10, bottom:0, left:2 } },
    plugins:{
      legend:{ display:false },
      tooltip:{
        backgroundColor:p.surface, titleColor:p.ink, bodyColor:p.ink2,
        borderColor:p.grid, borderWidth:1, padding:10, cornerRadius:6,
        titleFont:{ family:"IBM Plex Sans", weight:"600" },
        bodyFont:{ family:"IBM Plex Mono" }, displayColors:false,
      },
    },
    scales:{
      x:{ grid:{ color:p.grid, drawTicks:false }, border:{ color:p.grid },
          ticks:{ color:p.muted, font:{ family:"IBM Plex Mono", size:10 }, maxRotation:0, autoSkipPadding:16 } },
      y:{ grid:{ color:p.grid, drawTicks:false }, border:{ display:false },
          ticks:{ color:p.muted, font:{ family:"IBM Plex Mono", size:10 } } },
    },
  };
}

function fmtMonth(t){ const d = new Date(t); return d.toLocaleDateString("en-GB",{month:"short",year:"2-digit"}); }

function renderForecast(p){
  const el = $("#c-forecast"); const fc = DATA.forecast;
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!fc){ box(el, "No forecast yet — run the ukhpi + forecast steps."); return; }
  const aLabels = fc.actual.map(d => d.t);
  const fLabels = fc.forecast.map(d => d.t);
  const labels = aLabels.concat(fLabels);
  const n = aLabels.length;
  const pad = arr => new Array(n).fill(null).concat(arr);
  const actual = fc.actual.map(d => d.price).concat(new Array(fLabels.length).fill(null));
  // stitch: last actual point starts the forecast line so there's no gap
  const fcLine = new Array(n-1).fill(null).concat([fc.actual[n-1].price], fc.forecast.map(d=>d.price));
  const lo = pad(fc.forecast.map(d => d.lo95));
  const hi = pad(fc.forecast.map(d => d.hi95));
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = {
    title: it => fmtMonth(it[0].label),
    label: it => it.raw==null ? null : (it.datasetIndex===0?"Actual  ":"Forecast  ") + gbp0(it.raw),
  };
  o.scales.x.ticks.callback = function(v){ return fmtMonth(this.getLabelForValue(v)); };
  o.scales.x.ticks.maxTicksLimit = 9;
  o.scales.y.ticks.callback = v => gbpK(v);
  CHARTS.push(new Chart(el, { type:"line", data:{ labels, datasets:[
    { label:"Actual", data:actual, borderColor:p.accent, backgroundColor:p.accentSoft,
      borderWidth:2, pointRadius:0, tension:.25, fill:true },
    { label:"Forecast", data:fcLine, borderColor:p.orange, borderWidth:2, borderDash:[5,4],
      pointRadius:0, tension:.25, fill:false },
    { label:"lo95", data:lo, borderColor:"transparent", pointRadius:0,
      backgroundColor:p.accentSoft, fill:"+1" },
    { label:"hi95", data:hi, borderColor:"transparent", pointRadius:0, fill:false },
  ]}, options:o }));
  $("#fc-note").textContent =
    `${fc.last_actual_month}: ${gbp0(fc.last_actual_price)}  →  ${fc.projected_month}: ` +
    `${gbp0(fc.projected_price)} (${pct1(fc.projected_change_pct)}). 95% range ` +
    `${gbp0(fc.lo95)} – ${gbp0(fc.hi95)}.`;
}

function renderAsking(p){
  const el = $("#c-asking"); const s = DATA.asking_over_time || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(s.length===0){ box(el,"No snapshots yet."); return; }
  const one = s.length===1;
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label,
    label: it => it.dataset.label + "  " + gbp0(it.raw) };
  o.scales.y.ticks.callback = v => gbpK(v);
  const lo = Math.min(...s.map(d=>d.p25)), hi = Math.max(...s.map(d=>d.p75));
  o.scales.y.min = Math.floor((lo - (hi-lo)*0.25) / 10000) * 10000;
  o.scales.y.max = Math.ceil((hi + (hi-lo)*0.25) / 10000) * 10000;
  CHARTS.push(new Chart(el, { type:"line", data:{ labels:s.map(d=>d.t), datasets:[
    { label:"75th pct", data:s.map(d=>d.p75), borderColor:p.accent, borderWidth:1,
      borderDash:[3,3], pointRadius:one?3:0, pointBackgroundColor:p.accent,
      backgroundColor:p.accentSoft, fill:"+1" },
    { label:"25th pct", data:s.map(d=>d.p25), borderColor:p.accent, borderWidth:1,
      borderDash:[3,3], pointRadius:one?3:0, pointBackgroundColor:p.accent, fill:false },
    { label:"Median", data:s.map(d=>d.median), borderColor:p.accent, backgroundColor:p.accent,
      borderWidth:2, pointRadius:one?5:2, tension:.2, fill:false },
  ]}, options:o }));
}

function renderInventory(p){
  const el = $("#c-inventory"); const s = DATA.inventory_over_time || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(s.length===0){ box(el,"No snapshots yet."); return; }
  const one = s.length===1;
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label, label: it =>
    `${it.raw.toLocaleString("en-GB")} listings · ${s[it.dataIndex].pct_reduced.toFixed(1)}% reduced` };
  o.scales.y.ticks.callback = v => v.toLocaleString("en-GB");
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:s.map(d=>d.t), datasets:[
    { label:"Listings", data:s.map(d=>d.n_listings), backgroundColor:p.accent,
      borderRadius:3, barThickness: one?60:undefined, maxBarThickness:60 },
  ]}, options:o }));
}

function hbar(elId, rows, p, color){
  const el = $("#"+elId);
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!rows || rows.length===0){ box(el,"No data in the latest snapshot."); return; }
  const o = baseOpts(p);
  o.indexAxis = "y";
  o.plugins.tooltip.callbacks = { title: it=>rows[it[0].dataIndex].seg,
    label: it => `${gbp0(it.raw)}  ·  ${rows[it.dataIndex].n} listings` };
  o.scales.x.ticks.callback = v => gbpK(v);
  o.scales.y.ticks.font = { family:"IBM Plex Mono", size:11 };
  o.scales.y.afterFit = sc => { sc.width = Math.max(sc.width, 84); };
  const clip = s => s.length > 15 ? s.slice(0,14) + "…" : s;
  const labelPlugin = {
    id:"cnt"+elId,
    afterDatasetsDraw(ch){
      const {ctx} = ch; ctx.save();
      ctx.font = "10px 'IBM Plex Mono'"; ctx.fillStyle = p.muted; ctx.textBaseline = "middle";
      ch.getDatasetMeta(0).data.forEach((bar,i)=>{
        ctx.textAlign = "left";
        ctx.fillText(rows[i].n, bar.x + 6, bar.y);
      });
      ctx.restore();
    }
  };
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:rows.map(r=>clip(r.seg)),
    datasets:[{ data:rows.map(r=>r.median), backgroundColor:color, borderRadius:3,
      maxBarThickness:22 }] }, options:o, plugins:[labelPlugin] }));
}

function renderBeds(p){
  const el = $("#c-beds"); const rows = DATA.by_bedrooms || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(rows.length===0){ box(el,"No data."); return; }
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label==="Studio"?"Studio / 0-bed":it[0].label+" bed",
    label: it => `${gbp0(it.raw)} · ${rows[it.dataIndex].n} listings` };
  o.scales.y.ticks.callback = v => gbpK(v);
  const lp = { id:"bedcnt", afterDatasetsDraw(ch){
    const {ctx} = ch; ctx.save(); ctx.font = "10px 'IBM Plex Mono'"; ctx.fillStyle = p.muted;
    ctx.textAlign = "center";
    ch.getDatasetMeta(0).data.forEach((b,i)=>ctx.fillText(rows[i].n, b.x, b.y - 6));
    ctx.restore();
  }};
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:rows.map(r=>r.seg),
    datasets:[{ data:rows.map(r=>r.median), backgroundColor:p.accent, borderRadius:3, maxBarThickness:44 }] },
    options:o, plugins:[lp] }));
}

function renderDist(p){
  const el = $("#c-dist"); const d = DATA.price_distribution;
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!d || !d.counts.length){ box(el,"No data."); return; }
  const labels = d.edges.slice(0,-1).map(e => "£"+Math.round(e/1e3)+"k");
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label+" – "+labels[it[0].dataIndex+1] || "",
    label: it => it.raw + " listings" };
  o.scales.x.ticks.autoSkip = true; o.scales.x.ticks.maxTicksLimit = 8;
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels, datasets:[
    { data:d.counts, backgroundColor:p.accent, borderRadius:2, barPercentage:1, categoryPercentage:.92 }
  ]}, options:o }));
}

function renderQual(p){
  const el = $("#c-qual"); const q = DATA.price_qualifier || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(q.length===0){ box(el,"No data."); return; }
  const total = q.reduce((a,b)=>a+b.n,0);
  const o = baseOpts(p);
  o.indexAxis = "y";
  o.plugins.tooltip.callbacks = { title: it=>q[it[0].dataIndex].seg,
    label: it => `${it.raw} listings  ·  ${(100*it.raw/total).toFixed(0)}%` };
  o.scales.y.ticks.font = { family:"IBM Plex Mono", size:11 };
  o.scales.y.afterFit = sc => { sc.width = Math.max(sc.width, 128); };
  const clip = s => s.length > 18 ? s.slice(0,17) + "…" : s;
  const colors = q.map(r => /offers over/i.test(r.seg) ? p.orange : p.accent);
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:q.map(r=>clip(r.seg)),
    datasets:[{ data:q.map(r=>r.n), backgroundColor:colors, borderRadius:3, maxBarThickness:22 }] },
    options:o }));
}

function renderAreaRank(p){
  const el = $("#c-area-rank"); const rows = DATA.by_area || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(rows.length===0){ box(el,"No area data in the latest snapshot."); return; }
  const cityMed = DATA.city_median;
  const o = baseOpts(p);
  o.indexAxis = "y";
  o.layout.padding.right = 34;
  o.plugins.tooltip.callbacks = {
    title: it => `${rows[it[0].dataIndex].seg} · ${rows[it[0].dataIndex].name}`,
    label: it => {
      const r = rows[it.dataIndex];
      const vs = (r.vs_city>=0?"+":"") + (100*r.vs_city).toFixed(0) + "% vs city";
      return [`${gbp0(r.median)}  (${vs})`, `${r.n} listings · ${r.pct_reduced.toFixed(0)}% reduced`];
    },
  };
  o.scales.x.ticks.callback = v => gbpK(v);
  o.scales.y.ticks.font = { family:"IBM Plex Mono", size:11 };
  o.scales.y.afterFit = sc => { sc.width = Math.max(sc.width, 46); };
  const cnt = { id:"arcnt", afterDatasetsDraw(ch){
    const {ctx} = ch; ctx.save();
    ctx.font = "10px 'IBM Plex Mono'"; ctx.fillStyle = p.muted; ctx.textBaseline = "middle"; ctx.textAlign = "left";
    ch.getDatasetMeta(0).data.forEach((b,i)=>ctx.fillText(rows[i].n, b.x + 6, b.y));
    ctx.restore();
  }};
  const refline = { id:"arref", afterDatasetsDraw(ch){
    if(cityMed==null) return;
    const x = ch.scales.x.getPixelForValue(cityMed);
    const {top,bottom} = ch.chartArea; const {ctx} = ch;
    ctx.save();
    ctx.strokeStyle = p.ink2; ctx.setLineDash([4,3]); ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(x,top); ctx.lineTo(x,bottom); ctx.stroke();
    ctx.setLineDash([]); ctx.fillStyle = p.ink2; ctx.font = "9px 'IBM Plex Mono'"; ctx.textAlign = "center";
    ctx.fillText("city median", x, top - 3);
    ctx.restore();
  }};
  const colors = rows.map(r => r.vs_city < 0 ? p.aqua : p.accent);
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:rows.map(r=>r.seg),
    datasets:[{ data:rows.map(r=>r.median), backgroundColor:colors, borderRadius:3, maxBarThickness:20 }] },
    options:o, plugins:[cnt, refline] }));
}

function renderAreaTrend(p){
  const el = $("#c-area-trend"); const at = DATA.area_trend;
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!at || at.series.length===0){ box(el,"No area history yet."); return; }
  const ranked = (DATA.by_area || []).map(r => r.seg);
  const pick = ranked.slice(0,3).concat(ranked.slice(-3));
  const chosen = at.series.filter(s => pick.includes(s.seg))
    .sort((a,b) => ranked.indexOf(a.seg) - ranked.indexOf(b.seg));
  const one = at.dates.length < 2;
  const o = baseOpts(p);
  o.plugins.legend = { display:true, position:"bottom",
    labels:{ color:p.ink2, boxWidth:8, boxHeight:8, usePointStyle:true, pointStyle:"line",
      font:{ family:"IBM Plex Sans", size:10.5 } } };
  o.plugins.tooltip.callbacks = { title: it=>it[0].label,
    label: it => `${it.dataset.label}  ${gbp0(it.raw)}` };
  o.scales.y.ticks.callback = v => gbpK(v);
  CHARTS.push(new Chart(el, { type:"line", data:{ labels:at.dates,
    datasets: chosen.map((s,i)=>({
      label: s.seg, data: s.points, borderColor: p.cat[i % p.cat.length],
      backgroundColor: p.cat[i % p.cat.length], borderWidth:2, tension:.2,
      pointRadius: one?4:2, spanGaps:true,
    })) }, options:o }));
}

function renderAreaTable(){
  const host = $("#area-table"); if(!host) return;
  const rows = DATA.by_area || [];
  if(rows.length===0){ host.innerHTML = "<tr><td>No area data yet.</td></tr>"; return; }
  const mv = {}; (DATA.area_movers || []).forEach(m => mv[m.seg] = m);
  const hasDelta = Object.keys(mv).length > 0;
  const head = `<thead><tr><th>Area</th><th>Listings</th><th>Median asking</th>
    <th>vs city</th><th>% reduced</th><th>Median days</th>${hasDelta?"<th>Δ since first</th>":""}</tr></thead>`;
  const body = rows.map(r => {
    const vs = 100*r.vs_city;
    const vsc = vs<0 ? "neg" : (vs>0 ? "pos" : "");
    const dom = r.median_dom==null ? "—" : Math.round(r.median_dom);
    let dcell = "";
    if(hasDelta){
      const m = mv[r.seg];
      if(m){ const dc = m.pct<0?"neg":(m.pct>0?"pos":"");
        dcell = `<td class="${dc}">${pct1(m.pct)}</td>`; }
      else dcell = "<td>—</td>";
    }
    return `<tr><td>${r.name} <span class="oc">${r.seg}</span></td>
      <td>${r.n}</td><td>${gbp0(r.median)}</td>
      <td class="${vsc}">${vs>0?"+":""}${vs.toFixed(0)}%</td>
      <td>${r.pct_reduced.toFixed(0)}%</td><td>${dom}</td>${dcell}</tr>`;
  }).join("");
  host.innerHTML = head + "<tbody>" + body + "</tbody>";
}

function box(canvas, msg){
  const d = document.createElement("div");
  d.className = "empty"; d.textContent = msg;
  canvas.replaceWith(d);
}

function kpis(){
  const s = DATA.snapshot, h = DATA.ukhpi, f = DATA.forecast;
  const cells = [];
  if(s){
    cells.push(["Live listings", s.n_listings.toLocaleString("en-GB"), `${s.n_new_7d} new in 7 days`]);
    cells.push(["Median asking", gbp0(s.median_price), `IQR ${gbpK(s.p25_price)}–${gbpK(s.p75_price)}`]);
    cells.push(["Showing a price cut", s.pct_reduced.toFixed(0)+"%",
      `${Math.round(s.pct_reduced*s.n_listings/100)} of ${s.n_listings.toLocaleString("en-GB")}`]);
  }
  if(h){
    cells.push(["UK HPI avg price", gbp0(h.avg_price), `to ${h.latest_month}`]);
    cells.push(["HPI annual change", pct1(h.annual_change_pct),
      {t:"year to "+h.latest_month, c: h.annual_change_pct>=0?"up":"down"}]);
  }
  if(f){
    cells.push(["Forecast, 12 months", gbp0(f.projected_price),
      {t:pct1(f.projected_change_pct)+" vs now", c: f.projected_change_pct>=0?"up":"down"}]);
  }
  $("#kpis").innerHTML = cells.map(([k,v,d])=>{
    const dd = typeof d === "object" ? `<div class="d ${d.c}">${d.t}</div>` : `<div class="d">${d||""}</div>`;
    return `<div class="kpi"><div class="k">${k}</div><div class="v">${v}</div>${dd}</div>`;
  }).join("");
}

function renderAll(){
  destroyAll();
  const p = palette();
  kpis();
  renderForecast(p);
  renderAreaRank(p);
  renderAreaTrend(p);
  renderAreaTable();
  renderAsking(p);
  renderInventory(p);
  hbar("c-type", DATA.by_type, p, p.aqua);
  renderBeds(p);
  renderDist(p);
  renderQual(p);
}

$("#gen").textContent = DATA.generated_at;
$("#loc").textContent = DATA.location;
$("#nsnap").textContent = DATA.n_snapshots || 1;
if((DATA.n_snapshots||1) < 2){
  $("#ts-note").textContent =
    "Only one snapshot so far — these two panels become trend lines once the daily task has run for a week or two.";
}
// Render once fonts are ready so Chart.js measures label widths with the real
// face (otherwise IBM Plex Mono swaps in after layout and axis labels clip).
if(document.fonts && document.fonts.ready){
  document.fonts.ready.then(renderAll);
  setTimeout(() => { if(CHARTS.length===0) renderAll(); }, 1200);
} else {
  renderAll();
}
window.matchMedia("(prefers-color-scheme:dark)").addEventListener("change", renderAll);
new MutationObserver(renderAll).observe(document.documentElement, { attributes:true, attributeFilter:["data-theme"] });
</script>
"""
