"""Build a self-contained HTML dashboard from the processed data.

Reads whatever exists under ``data/processed`` and the latest raw snapshot, and
writes ``data/processed/dashboard.html`` — a single file you can open in a
browser or publish. Regenerated by ``cli.py dashboard`` and at the end of
``cli.py all``.
"""
from __future__ import annotations

import json
from datetime import date, datetime, timezone

import numpy as np
import pandas as pd

from .areas import area_short
from .config import Config
from .loft_finder import new_since_previous_snapshot, score_listings, update_loft_history

CORE_OUTCODES = [f"EH{i}" for i in range(1, 18)]
BED_ORDER = ["Studio", "1", "2", "3", "4", "5", "6+"]
AREA_MIN_LISTINGS = 8  # ignore very thin districts in the area views
LOFT_MIN_SCORE = 3  # at least one strong hit, or two supporting ones


# --------------------------------------------------------------------------- #
# Payload
# --------------------------------------------------------------------------- #
def _latest_raw(cfg: Config) -> pd.DataFrame:
    files = sorted(cfg.raw_rightmove_dir.glob(f"{cfg.rightmove.location_slug}_*.parquet"))
    if not files:
        return pd.DataFrame()
    df = pd.read_parquet(files[-1])
    df = df[df["price"].notna() & (df["price"] > 0)].copy()
    df["first_visible_date"] = pd.to_datetime(
        df["first_visible_date"], errors="coerce", utc=True
    )
    return df


def _bed_bucket(n) -> str | None:
    if pd.isna(n):
        return None
    n = int(n)
    if n <= 0:
        return "Studio"
    if n >= 6:
        return "6+"
    return str(n)


def _histogram(prices: pd.Series) -> dict:
    if prices.empty:
        return {"edges": [], "counts": []}
    cap = float(min(prices.quantile(0.98), 1_500_000))
    edges = list(np.arange(0, cap + 50_000, 50_000))
    counts, _ = np.histogram(prices.clip(upper=cap), bins=edges)
    return {"edges": [int(e) for e in edges], "counts": [int(c) for c in counts]}


def build_payload(cfg: Config) -> dict:
    P = cfg.processed_dir
    raw = _latest_raw(cfg)

    payload: dict = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "location": cfg.rightmove.location_name,
    }

    # --- latest Rightmove snapshot ------------------------------------------
    if not raw.empty:
        snap_day = str(raw["snapshot_date"].iloc[0])
        price = raw["price"]
        dom = (pd.Timestamp(snap_day, tz="UTC") - raw["first_visible_date"]).dt.days
        payload["snapshot"] = {
            "date": snap_day,
            "n_listings": int(len(raw)),
            "median_price": float(price.median()),
            "mean_price": float(price.mean()),
            "p25_price": float(price.quantile(0.25)),
            "p75_price": float(price.quantile(0.75)),
            "pct_reduced": float(100 * (raw["added_or_reduced_kind"] == "Reduced").mean()),
            "n_new_7d": int((dom <= 7).sum()),
            "n_new_30d": int((dom <= 30).sum()),
            "median_days_on_market": float(dom.median()) if dom.notna().any() else None,
        }
        city_median = float(price.median())
        by_area = []
        for oc in CORE_OUTCODES:
            sub = raw.loc[raw["outcode"] == oc, "price"]
            if len(sub) < 3:
                continue
            reduced = raw.loc[raw["outcode"] == oc, "added_or_reduced_kind"]
            dom_oc = dom[raw["outcode"] == oc]
            latlon = raw.loc[raw["outcode"] == oc, ["latitude", "longitude"]].dropna()
            by_area.append({
                "seg": oc,
                "name": area_short(oc),
                "n": int(len(sub)),
                "median": float(sub.median()),
                "p25": float(sub.quantile(0.25)),
                "p75": float(sub.quantile(0.75)),
                "vs_city": float(sub.median() / city_median - 1),
                "pct_reduced": float(100 * (reduced == "Reduced").mean()),
                "median_dom": float(dom_oc.median()) if dom_oc.notna().any() else None,
                "lat": float(latlon["latitude"].median()) if not latlon.empty else None,
                "lon": float(latlon["longitude"].median()) if not latlon.empty else None,
            })
        by_area.sort(key=lambda r: r["median"])
        payload["by_outcode"] = [
            {"seg": r["seg"], "n": r["n"], "median": r["median"]} for r in by_area
        ]
        payload["by_area"] = by_area
        payload["city_median"] = city_median
        by_type = (
            raw.groupby("property_sub_type")["price"]
            .agg(["size", "median"]).reset_index()
            .sort_values("size", ascending=False).head(9)
        )
        payload["by_type"] = [
            {"seg": r["property_sub_type"], "n": int(r["size"]), "median": float(r["median"])}
            for _, r in by_type.iterrows()
        ]
        raw["_bed"] = raw["bedrooms"].map(_bed_bucket)
        by_bed = raw.dropna(subset=["_bed"]).groupby("_bed")["price"].agg(["size", "median"])
        payload["by_bedrooms"] = [
            {"seg": b, "n": int(by_bed.loc[b, "size"]), "median": float(by_bed.loc[b, "median"])}
            for b in BED_ORDER if b in by_bed.index
        ]
        qual = raw["price_qualifier"].fillna("Not specified").value_counts().head(7)
        payload["price_qualifier"] = [
            {"seg": k, "n": int(v)} for k, v in qual.items()
        ]
        payload["price_distribution"] = _histogram(price)

        scored = score_listings(raw)
        candidates = scored[scored["loft_score"] >= LOFT_MIN_SCORE].sort_values(
            ["loft_score", "price"], ascending=[False, True]
        )

        new_ids: set[str] = set()
        n_dropped = 0
        if not candidates.empty:
            hist = update_loft_history(cfg, candidates, snap_day)
            new_ids, n_dropped = new_since_previous_snapshot(hist, snap_day)

        payload["loft_candidates"] = [
            {
                "id": r["id"],
                "score": int(r["loft_score"]),
                "matches": [m.strip() for m in r["loft_matches"].split(",") if m.strip()],
                "price": float(r["price"]),
                "price_qualifier": _s(r.get("price_qualifier")),
                "bedrooms": _to_int_or_none(r.get("bedrooms")),
                "property_sub_type": _s(r.get("property_sub_type")),
                "display_address": _s(r.get("display_address")),
                "outcode": _s(r.get("outcode")),
                "size_sqft": _to_int_or_none(r.get("size_sqft")),
                "added_or_reduced": _s(r.get("added_or_reduced")),
                "first_visible_date": _iso(r.get("first_visible_date")),
                "branch_name": _s(r.get("branch_name")),
                "property_url": _s(r.get("property_url")),
                "is_new": str(r["id"]) in new_ids,
            }
            for _, r in candidates.head(60).iterrows()
        ]
        payload["loft_text_available"] = bool(
            "summary" in raw.columns or "key_features" in raw.columns
        )
        payload["loft_new_count"] = len(new_ids)
        payload["loft_dropped_count"] = n_dropped

    # --- Rightmove series over time --------------------------------------
    ts_path = P / "market_timeseries.csv"
    if ts_path.exists():
        ts = pd.read_csv(ts_path)
        payload["asking_over_time"] = [
            {"t": r["snapshot_date"], "median": _f(r["median_price"]),
             "p25": _f(r["p25_price"]), "p75": _f(r["p75_price"]), "n": int(r["n_listings"])}
            for _, r in ts.iterrows()
        ]
        payload["inventory_over_time"] = [
            {"t": r["snapshot_date"], "n_listings": int(r["n_listings"]),
             "pct_reduced": _f(r["pct_reduced"]), "median_dom": _f(r["median_days_on_market"])}
            for _, r in ts.iterrows()
        ]

    # --- median asking price by area, over time -------------------------
    seg_path = P / "market_timeseries_by_segment.csv"
    if seg_path.exists():
        seg = pd.read_csv(seg_path)
        seg = seg[seg["segment_kind"] == "outcode"].copy()
        if not seg.empty:
            dates = sorted(seg["snapshot_date"].unique())
            latest = dates[-1]
            keep = set(
                seg.loc[(seg["snapshot_date"] == latest) & (seg["n_listings"] >= AREA_MIN_LISTINGS),
                        "segment"]
            )
            series, movers = [], []
            for oc in sorted(keep, key=lambda o: int(o[2:])):
                rows = seg[seg["segment"] == oc].set_index("snapshot_date")
                pts = [_f(rows["median_price"].get(d)) for d in dates]
                series.append({"seg": oc, "name": area_short(oc), "points": pts})
                have = [(d, rows["median_price"].get(d)) for d in dates
                        if pd.notna(rows["median_price"].get(d))]
                if len(have) >= 2:
                    first_p, last_p = have[0][1], have[-1][1]
                    movers.append({
                        "seg": oc, "name": area_short(oc),
                        "first": float(first_p), "last": float(last_p),
                        "abs": float(last_p - first_p),
                        "pct": float(100 * (last_p / first_p - 1)),
                        "from": have[0][0], "to": have[-1][0],
                    })
            movers.sort(key=lambda r: r["pct"], reverse=True)
            payload["area_trend"] = {"dates": list(dates), "series": series}
            payload["area_movers"] = movers

    # --- UK HPI + forecast ------------------------------------------------
    hpi_path = cfg.raw_ukhpi_dir / f"ukhpi_{cfg.ukhpi.region_slug}.csv"
    if hpi_path.exists():
        hpi = pd.read_csv(hpi_path).dropna(subset=["averagePrice"])
        latest = hpi.iloc[-1]
        payload["ukhpi"] = {
            "latest_month": str(latest["month"]),
            "avg_price": float(latest["averagePrice"]),
            "annual_change_pct": _f(latest["percentageAnnualChange"]),
            "index": _f(latest["housePriceIndex"]),
            "history": [
                {"t": r["month"], "price": float(r["averagePrice"])}
                for _, r in hpi.iterrows()
            ],
        }

    fc_path = P / "forecast_ukhpi.csv"
    if fc_path.exists():
        fc = pd.read_csv(fc_path)
        act = fc[fc["kind"] == "actual"]
        fut = fc[fc["kind"] == "forecast"]
        if not fut.empty:
            last_actual = float(act["avg_price"].iloc[-1])
            proj = float(fut["avg_price"].iloc[-1])
            payload["forecast"] = {
                "horizon_months": int(len(fut)),
                "last_actual_price": last_actual,
                "last_actual_month": str(pd.to_datetime(act["date"].iloc[-1]).date()),
                "projected_price": proj,
                "projected_month": str(pd.to_datetime(fut["date"].iloc[-1]).date()),
                "projected_change_pct": 100 * (proj / last_actual - 1),
                "lo95": float(fut["lo95"].iloc[-1]),
                "hi95": float(fut["hi95"].iloc[-1]),
                "actual": [
                    {"t": str(pd.to_datetime(r["date"]).date()), "price": float(r["avg_price"])}
                    for _, r in act.tail(120).iterrows()
                ],
                "forecast": [
                    {"t": str(pd.to_datetime(r["date"]).date()), "price": float(r["avg_price"]),
                     "lo80": _f(r["lo80"]), "hi80": _f(r["hi80"]),
                     "lo95": _f(r["lo95"]), "hi95": _f(r["hi95"])}
                    for _, r in fut.iterrows()
                ],
            }

    # --- run history ----------------------------------------------------
    idx_path = P / "snapshot_index.csv"
    if idx_path.exists():
        payload["n_snapshots"] = int(len(pd.read_csv(idx_path)))

    return payload


def _f(v):
    return None if pd.isna(v) else float(v)


def _to_int_or_none(v):
    return None if pd.isna(v) else int(v)


def _s(v):
    """None-safe passthrough for pandas string columns (NaN is truthy in `x or None`)."""
    return None if pd.isna(v) else v


def _iso(v):
    """None-safe ISO string for a pandas Timestamp (json.dumps can't serialize those directly)."""
    if pd.isna(v):
        return None
    return v.isoformat() if hasattr(v, "isoformat") else str(v)


# --------------------------------------------------------------------------- #
# Render
# --------------------------------------------------------------------------- #
def render_html(payload: dict, *, standalone: bool = True) -> str:
    data_json = json.dumps(payload, allow_nan=False)
    content = _TEMPLATE.replace("__DATA__", data_json)
    if not standalone:
        return content
    return (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "<style>body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>\n"
        "</head>\n<body>\n" + content + "\n</body>\n</html>\n"
    )


def build_dashboard(cfg: Config) -> dict:
    cfg.ensure_dirs()
    payload = build_payload(cfg)
    out = cfg.processed_dir / "dashboard.html"
    out.write_text(render_html(payload, standalone=True), encoding="utf-8")
    # Body-only fragment, handy for publishing as an Artifact.
    (cfg.processed_dir / "dashboard.fragment.html").write_text(
        render_html(payload, standalone=False), encoding="utf-8"
    )
    snap = payload.get("snapshot", {})
    print(f"  dashboard -> {out}")
    if snap:
        print(
            f"  {snap['date']}: {snap['n_listings']} listings, median asking "
            f"£{snap['median_price']:,.0f}, {snap['pct_reduced']:.0f}% reduced"
        )
    return payload


# --------------------------------------------------------------------------- #
# Template  (title + styles + markup + inline chart script)
# --------------------------------------------------------------------------- #
_TEMPLATE = r"""
<title>Edinburgh Housing Monitor</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<style>
  :root{
    --page:#f4f5f7; --surface:#ffffff; --surface-2:#fafbfc;
    --ink:#14161a; --ink-2:#565b62; --muted:#878b91;
    --grid:#e6e8eb; --hair:rgba(20,22,26,.10);
    --accent:#2a78d6; --accent-soft:rgba(42,120,214,.12);
    --orange:#eb6834; --aqua:#1baf7a; --warn:#c98500; --down:#b23b2e; --up:#006300;
    --c1:#2a78d6; --c2:#eb6834; --c3:#1baf7a; --c4:#eda100; --c5:#e87ba4; --c6:#4a3aa7;
    --radius:10px;
    --sans:"IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif;
    --mono:"IBM Plex Mono",ui-monospace,"SF Mono",Menlo,Consolas,monospace;
  }
  @media (prefers-color-scheme:dark){
    :root:not([data-theme="light"]){
      --page:#0e0e10; --surface:#1a1a1c; --surface-2:#202024;
      --ink:#f3f4f6; --ink-2:#b9bcc2; --muted:#8a8e95;
      --grid:#2a2b2e; --hair:rgba(255,255,255,.12);
      --accent:#3987e5; --accent-soft:rgba(57,135,229,.16);
      --orange:#d95926; --aqua:#199e70; --warn:#e0a838; --down:#e8705d; --up:#4fb04f;
      --c1:#3987e5; --c2:#d95926; --c3:#199e70; --c4:#c98500; --c5:#d55181; --c6:#9085e9;
    }
  }
  :root[data-theme="dark"]{
    --page:#0e0e10; --surface:#1a1a1c; --surface-2:#202024;
    --ink:#f3f4f6; --ink-2:#b9bcc2; --muted:#8a8e95;
    --grid:#2a2b2e; --hair:rgba(255,255,255,.12);
    --accent:#3987e5; --accent-soft:rgba(57,135,229,.16);
    --orange:#d95926; --aqua:#199e70; --warn:#e0a838; --down:#e8705d; --up:#4fb04f;
    --c1:#3987e5; --c2:#d95926; --c3:#199e70; --c4:#c98500; --c5:#d55181; --c6:#9085e9;
  }

  *{box-sizing:border-box}
  body{margin:0;background:var(--page);color:var(--ink);font-family:var(--sans);
    -webkit-font-smoothing:antialiased;line-height:1.5}
  .wrap{max-width:1080px;margin:0 auto;padding:40px 24px 72px}

  header{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px 16px;
    padding-bottom:20px;border-bottom:1px solid var(--hair);margin-bottom:28px}
  h1{font-size:23px;font-weight:700;letter-spacing:-.01em;margin:0}
  .sub{color:var(--ink-2);font-size:13px}
  .sub .mono{font-family:var(--mono);color:var(--ink)}

  h2{font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.09em;
    color:var(--muted);margin:36px 0 14px}
  h2:first-of-type{margin-top:8px}

  .kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;
    background:var(--hair);border:1px solid var(--hair);border-radius:var(--radius);overflow:hidden}
  @media (max-width:860px){.kpis{grid-template-columns:repeat(3,1fr)}}
  @media (max-width:480px){.kpis{grid-template-columns:repeat(2,1fr)}}
  .kpi{background:var(--surface);padding:15px 16px 14px}
  .kpi .k{font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}
  .kpi .v{font-family:var(--mono);font-size:21px;font-weight:600;margin-top:6px;letter-spacing:-.01em}
  .kpi .d{font-size:11.5px;color:var(--ink-2);margin-top:3px}
  .kpi .d.down{color:var(--down)} .kpi .d.up{color:var(--up)}

  .card{background:var(--surface);border:1px solid var(--hair);border-radius:var(--radius);
    padding:18px 18px 14px}
  .card .ct{font-size:13.5px;font-weight:600;margin:0 0 2px}
  .card .cs{font-size:12px;color:var(--ink-2);margin:0 0 12px}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  .grid3{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  @media (max-width:720px){.grid2,.grid3{grid-template-columns:1fr}}

  .chartbox{position:relative;width:100%}
  .h-hero{height:340px} .h-med{height:240px} .h-tall{height:300px}

  .note{font-size:12px;color:var(--muted);font-style:italic;margin-top:10px}
  .empty{display:flex;align-items:center;justify-content:center;height:100%;
    color:var(--muted);font-size:12.5px;text-align:center;padding:0 24px}

  .lt{width:100%;border-collapse:collapse;font-size:12.5px}
  .lt th{text-align:right;font-weight:600;color:var(--muted);font-size:10.5px;
    text-transform:uppercase;letter-spacing:.06em;padding:0 10px 8px;border-bottom:1px solid var(--hair)}
  .lt th:first-child,.lt td:first-child{text-align:left}
  .lt td{padding:8px 10px;border-bottom:1px solid var(--hair);
    font-family:var(--mono);font-variant-numeric:tabular-nums;color:var(--ink-2)}
  .lt td:first-child{font-family:var(--sans);color:var(--ink)}
  .lt tr:last-child td{border-bottom:0}
  .lt .pos{color:var(--up)} .lt .neg{color:var(--down)}
  .lt .oc{color:var(--muted);font-family:var(--mono);font-size:11px}
  .scroller{overflow-x:auto}

  .loft-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;
    flex-wrap:wrap;margin-bottom:12px}
  .loft-count{font-size:12px;color:var(--ink-2)}
  .loft-count b{color:var(--ink);font-family:var(--mono)}
  .loft-count .delta-new{color:var(--up);font-weight:600}
  .loft-count .delta-gone{color:var(--muted)}
  .btn{font:600 12px var(--sans);color:#fff;background:var(--accent);border:none;
    border-radius:7px;padding:7px 13px;cursor:pointer;white-space:nowrap}
  .btn:hover{filter:brightness(1.08)}
  .btn:active{filter:brightness(.94)}
  .btn-note{font-size:10.5px;color:var(--muted);margin-top:6px}

  .seg{display:inline-flex;border:1px solid var(--hair);border-radius:7px;overflow:hidden}
  .seg-btn{font:600 11.5px var(--sans);color:var(--ink-2);background:var(--surface);
    border:none;border-right:1px solid var(--hair);padding:6px 11px;cursor:pointer;white-space:nowrap}
  .seg-btn:last-child{border-right:0}
  .seg-btn:hover{background:var(--surface-2)}
  .seg-btn.active{background:var(--accent);color:#fff}

  .loft-list{display:flex;flex-direction:column;border:1px solid var(--hair);border-radius:var(--radius);
    overflow:hidden}
  .loft-row{display:flex;align-items:center;gap:14px;padding:11px 15px;background:var(--surface);
    border-bottom:1px solid var(--hair)}
  .loft-row:last-child{border-bottom:0}
  .loft-row:nth-child(even){background:var(--surface-2)}
  .loft-row.is-new{box-shadow:inset 3px 0 0 var(--up)}
  .loft-new-tag{flex:0 0 auto;font-family:var(--mono);font-size:9.5px;font-weight:700;
    letter-spacing:.04em;color:var(--up);background:color-mix(in srgb, var(--up) 14%, transparent);
    padding:3px 7px;border-radius:99px;white-space:nowrap}
  .loft-score{flex:0 0 auto;font-family:var(--mono);font-size:10.5px;font-weight:600;
    padding:3px 9px;border-radius:99px;white-space:nowrap}
  .loft-score.strong{background:var(--accent-soft);color:var(--accent)}
  .loft-score.maybe{background:var(--surface-2);color:var(--ink-2);border:1px solid var(--hair)}
  .loft-price{flex:0 0 92px;font-family:var(--mono);font-size:14px;font-weight:600;letter-spacing:-.01em}
  .loft-qual{flex:0 0 108px;font-size:10.5px;color:var(--muted);line-height:1.3}
  .loft-main{flex:1 1 auto;min-width:0}
  .loft-addr{font-size:12.5px;color:var(--ink);line-height:1.3;white-space:nowrap;overflow:hidden;
    text-overflow:ellipsis}
  .loft-meta{font-size:11px;color:var(--ink-2);margin-top:1px}
  .loft-chips{display:flex;flex-wrap:wrap;gap:4px;margin-top:4px}
  .loft-chip{font-size:10px;padding:1px 7px;border-radius:99px;background:var(--surface-2);
    border:1px solid var(--hair);color:var(--ink-2)}
  .loft-foot{flex:0 0 128px;text-align:right;font-size:10.5px;color:var(--muted);line-height:1.35}
  .loft-foot a{display:inline-block;margin-top:3px;font-weight:600;text-decoration:none}
  .loft-foot a:hover{text-decoration:underline}
  @media (max-width:760px){
    .loft-row{flex-wrap:wrap}
    .loft-qual{display:none}
    .loft-foot{flex-basis:100%;text-align:left;margin-top:4px}
  }

  .loft-tip{font-size:12.5px;color:var(--ink-2);background:var(--surface-2);border:1px solid var(--hair);
    border-radius:8px;padding:11px 13px;margin-top:14px;line-height:1.55}

  footer{margin-top:44px;padding-top:18px;border-top:1px solid var(--hair);
    font-size:12px;color:var(--muted)}
  footer b{color:var(--ink-2);font-weight:600}
  a{color:var(--accent)}
</style>

<div class="wrap">
  <header>
    <h1>Edinburgh Housing Monitor</h1>
    <span class="sub">Rightmove asking prices &amp; stock vs the official UK House Price Index &nbsp;·&nbsp;
      generated <span class="mono" id="gen"></span></span>
  </header>

  <h2>Where the market is now</h2>
  <div class="kpis" id="kpis"></div>

  <h2>Sold-price benchmark &amp; forecast</h2>
  <div class="card">
    <p class="ct">City of Edinburgh average sold price — UK HPI, with 12-month projection</p>
    <p class="cs" id="fc-cs">Seasonal ARIMA on the UK House Price Index (incorporates Registers of Scotland). Shaded band = 95% interval.</p>
    <div class="chartbox h-hero"><canvas id="c-forecast"></canvas></div>
    <p class="note" id="fc-note"></p>
  </div>

  <h2>Cheaper vs dearer — Edinburgh by area</h2>
  <div class="card">
    <p class="ct">Median asking price by area</p>
    <p class="cs">Postcode districts, cheapest to dearest. Dashed line = city median. Numbers after each bar are listing counts.</p>
    <div class="chartbox h-tall"><canvas id="c-area-rank"></canvas></div>
  </div>
  <div class="card" style="margin-top:16px">
    <p class="ct">How every area is trending</p>
    <p class="cs" id="area-trend-cs">Median asking price per snapshot, every district on one chart. Lines are
      shaded by price level (light = cheap, dark = dear) and labelled at the right-hand end — hover a line for its
      exact values.</p>
    <div class="chartbox h-tall" style="height:420px"><canvas id="c-area-trend"></canvas></div>
  </div>
  <div class="card" style="margin-top:16px">
    <p class="ct">Area league table</p>
    <p class="cs" id="area-table-cs">Every district with 3+ listings today, cheapest first. &ldquo;vs city&rdquo; compares the area median to the whole-city median.</p>
    <div class="scroller"><table class="lt" id="area-table"></table></div>
  </div>

  <h2>Open-plan industrial lofts &amp; warehouse conversions</h2>
  <div class="card">
    <p class="ct">Today's closest matches</p>
    <p class="cs" id="loft-cs">Every current listing's description and key features, scanned for warehouse/loft/mill-conversion
      language (warehouse, foundry, printworks, bonded warehouse…) and supporting decor cues (exposed brick, mezzanine,
      double-height, exposed concrete/ductwork, open plan…). Re-scanned fresh every day, so this isn't the same fixed
      list — sort by newest to see what's changed, and new matches are flagged.</p>
    <div class="loft-actions">
      <span class="loft-count"><b id="loft-n">0</b> matches<span id="loft-delta"></span></span>
      <span class="seg" id="loft-sort" role="group" aria-label="Sort">
        <button class="seg-btn active" data-sort="score" type="button">Best match</button>
        <button class="seg-btn" data-sort="new" type="button">Newest listed</button>
      </span>
      <button class="btn" id="loft-open-all" type="button">Open all in new tabs ↗</button>
    </div>
    <div id="loft-grid" class="loft-list"></div>
    <p class="btn-note">Some browsers block more than one tab opening at once — if that happens, allow pop-ups for
      this page and click again.</p>
    <p class="loft-tip">Edinburgh's own industrial-conversion stock clusters in a handful of places worth watching
      directly, scan or not: <b>Leith</b> (EH6) — converted whisky bonds and warehouses around the Shore and
      Bonnington; <b>Tanfield / Canonmills</b> (EH3) — the former print works, a well-known loft development;
      <b>Powderhall</b> (EH7) — the old foundry/waste-works site, exposed brick and steel; and <b>Fountainbridge</b>
      (EH3/EH11) — former brewery and rubber-works land, mostly new-build in an industrial idiom rather than true
      conversions. This list re-scans automatically every day the monitor runs.</p>
  </div>

  <h2>Rightmove asking prices &amp; stock over time</h2>
  <div class="grid2">
    <div class="card">
      <p class="ct">Median asking price</p>
      <p class="cs">Interquartile range shaded. One point per daily snapshot.</p>
      <div class="chartbox h-med"><canvas id="c-asking"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">Live listings on the market</p>
      <p class="cs">Total stock per snapshot. Hover for the share showing a price cut.</p>
      <div class="chartbox h-med"><canvas id="c-inventory"></canvas></div>
    </div>
  </div>
  <p class="note" id="ts-note"></p>

  <h2>Today's stock, broken down</h2>
  <div class="grid2">
    <div class="card">
      <p class="ct">Median asking price by property type</p>
      <p class="cs">Most common types in the current snapshot.</p>
      <div class="chartbox h-tall"><canvas id="c-type"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">Median asking price by bedroom count</p>
      <p class="cs">Bars labelled with listing counts. 0-bed = parking, land and studios.</p>
      <div class="chartbox h-tall"><canvas id="c-beds"></canvas></div>
    </div>
  </div>
  <div class="grid2" style="margin-top:16px">
    <div class="card">
      <p class="ct">Asking price distribution</p>
      <p class="cs">All priced listings, £50k bins, top 2% clipped.</p>
      <div class="chartbox h-med"><canvas id="c-dist"></canvas></div>
    </div>
    <div class="card">
      <p class="ct">How prices are quoted</p>
      <p class="cs">Mostly <em>Offers Over</em> — the asking figure is a floor, and the sale usually closes above it.</p>
      <div class="chartbox h-med"><canvas id="c-qual"></canvas></div>
    </div>
  </div>

  <footer>
    <p><b>Reading this.</b> The UK HPI is the lagging ground truth (actual sold prices, ~2 months behind).
    The Rightmove series leads it — asking prices, stock and discounting turn first. The forecast currently
    uses UK HPI history only; Rightmove momentum joins as an input once several months of snapshots accrue.</p>
    <p style="margin-top:8px"><b>Sources.</b> Rightmove for-sale listings for <span id="loc"></span> (personal research, one sweep per day).
    UK House Price Index, HM Land Registry / Registers of Scotland, City of Edinburgh series.
    Snapshots to date: <span id="nsnap">1</span>.</p>
  </footer>
</div>

<script>
const DATA = __DATA__;
const $ = s => document.querySelector(s);

const gbp0 = n => "£" + Math.round(n).toLocaleString("en-GB");
const gbpK = n => n >= 1e6 ? "£" + (n/1e6).toFixed(2) + "m" : "£" + Math.round(n/1e3) + "k";
const pct1 = n => (n>0?"+":"") + n.toFixed(1) + "%";

function tok(name){ return getComputedStyle(document.documentElement).getPropertyValue(name).trim(); }
function palette(){
  return {
    ink: tok("--ink"), ink2: tok("--ink-2"), muted: tok("--muted"),
    grid: tok("--grid"), surface: tok("--surface"),
    accent: tok("--accent"), accentSoft: tok("--accent-soft"),
    orange: tok("--orange"), aqua: tok("--aqua"), warn: tok("--warn"),
    down: tok("--down"), up: tok("--up"),
    cat: [tok("--c1"), tok("--c2"), tok("--c3"), tok("--c4"), tok("--c5"), tok("--c6")],
  };
}

let CHARTS = [];
function destroyAll(){ CHARTS.forEach(c => c.destroy()); CHARTS = []; }

function baseOpts(p){
  return {
    responsive:true, maintainAspectRatio:false, animation:false,
    interaction:{ mode:"index", intersect:false },
    layout:{ padding:{ top:6, right:10, bottom:0, left:2 } },
    plugins:{
      legend:{ display:false },
      tooltip:{
        backgroundColor:p.surface, titleColor:p.ink, bodyColor:p.ink2,
        borderColor:p.grid, borderWidth:1, padding:10, cornerRadius:6,
        titleFont:{ family:"IBM Plex Sans", weight:"600" },
        bodyFont:{ family:"IBM Plex Mono" }, displayColors:false,
      },
    },
    scales:{
      x:{ grid:{ color:p.grid, drawTicks:false }, border:{ color:p.grid },
          ticks:{ color:p.muted, font:{ family:"IBM Plex Mono", size:10 }, maxRotation:0, autoSkipPadding:16 } },
      y:{ grid:{ color:p.grid, drawTicks:false }, border:{ display:false },
          ticks:{ color:p.muted, font:{ family:"IBM Plex Mono", size:10 } } },
    },
  };
}

function fmtMonth(t){ const d = new Date(t); return d.toLocaleDateString("en-GB",{month:"short",year:"2-digit"}); }

function renderForecast(p){
  const el = $("#c-forecast"); const fc = DATA.forecast;
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!fc){ box(el, "No forecast yet — run the ukhpi + forecast steps."); return; }
  const aLabels = fc.actual.map(d => d.t);
  const fLabels = fc.forecast.map(d => d.t);
  const labels = aLabels.concat(fLabels);
  const n = aLabels.length;
  const pad = arr => new Array(n).fill(null).concat(arr);
  const actual = fc.actual.map(d => d.price).concat(new Array(fLabels.length).fill(null));
  // stitch: last actual point starts the forecast line so there's no gap
  const fcLine = new Array(n-1).fill(null).concat([fc.actual[n-1].price], fc.forecast.map(d=>d.price));
  const lo = pad(fc.forecast.map(d => d.lo95));
  const hi = pad(fc.forecast.map(d => d.hi95));
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = {
    title: it => fmtMonth(it[0].label),
    label: it => it.raw==null ? null : (it.datasetIndex===0?"Actual  ":"Forecast  ") + gbp0(it.raw),
  };
  o.scales.x.ticks.callback = function(v){ return fmtMonth(this.getLabelForValue(v)); };
  o.scales.x.ticks.maxTicksLimit = 9;
  o.scales.y.ticks.callback = v => gbpK(v);
  CHARTS.push(new Chart(el, { type:"line", data:{ labels, datasets:[
    { label:"Actual", data:actual, borderColor:p.accent, backgroundColor:p.accentSoft,
      borderWidth:2, pointRadius:0, tension:.25, fill:true },
    { label:"Forecast", data:fcLine, borderColor:p.orange, borderWidth:2, borderDash:[5,4],
      pointRadius:0, tension:.25, fill:false },
    { label:"lo95", data:lo, borderColor:"transparent", pointRadius:0,
      backgroundColor:p.accentSoft, fill:"+1" },
    { label:"hi95", data:hi, borderColor:"transparent", pointRadius:0, fill:false },
  ]}, options:o }));
  $("#fc-note").textContent =
    `${fc.last_actual_month}: ${gbp0(fc.last_actual_price)}  →  ${fc.projected_month}: ` +
    `${gbp0(fc.projected_price)} (${pct1(fc.projected_change_pct)}). 95% range ` +
    `${gbp0(fc.lo95)} – ${gbp0(fc.hi95)}.`;
}

function renderAsking(p){
  const el = $("#c-asking"); const s = DATA.asking_over_time || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(s.length===0){ box(el,"No snapshots yet."); return; }
  const one = s.length===1;
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label,
    label: it => it.dataset.label + "  " + gbp0(it.raw) };
  o.scales.y.ticks.callback = v => gbpK(v);
  const lo = Math.min(...s.map(d=>d.p25)), hi = Math.max(...s.map(d=>d.p75));
  o.scales.y.min = Math.floor((lo - (hi-lo)*0.25) / 10000) * 10000;
  o.scales.y.max = Math.ceil((hi + (hi-lo)*0.25) / 10000) * 10000;
  CHARTS.push(new Chart(el, { type:"line", data:{ labels:s.map(d=>d.t), datasets:[
    { label:"75th pct", data:s.map(d=>d.p75), borderColor:p.accent, borderWidth:1,
      borderDash:[3,3], pointRadius:one?3:0, pointBackgroundColor:p.accent,
      backgroundColor:p.accentSoft, fill:"+1" },
    { label:"25th pct", data:s.map(d=>d.p25), borderColor:p.accent, borderWidth:1,
      borderDash:[3,3], pointRadius:one?3:0, pointBackgroundColor:p.accent, fill:false },
    { label:"Median", data:s.map(d=>d.median), borderColor:p.accent, backgroundColor:p.accent,
      borderWidth:2, pointRadius:one?5:2, tension:.2, fill:false },
  ]}, options:o }));
}

function renderInventory(p){
  const el = $("#c-inventory"); const s = DATA.inventory_over_time || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(s.length===0){ box(el,"No snapshots yet."); return; }
  const one = s.length===1;
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label, label: it =>
    `${it.raw.toLocaleString("en-GB")} listings · ${s[it.dataIndex].pct_reduced.toFixed(1)}% reduced` };
  o.scales.y.ticks.callback = v => v.toLocaleString("en-GB");
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:s.map(d=>d.t), datasets:[
    { label:"Listings", data:s.map(d=>d.n_listings), backgroundColor:p.accent,
      borderRadius:3, barThickness: one?60:undefined, maxBarThickness:60 },
  ]}, options:o }));
}

function hbar(elId, rows, p, color){
  const el = $("#"+elId);
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!rows || rows.length===0){ box(el,"No data in the latest snapshot."); return; }
  const o = baseOpts(p);
  o.indexAxis = "y";
  o.plugins.tooltip.callbacks = { title: it=>rows[it[0].dataIndex].seg,
    label: it => `${gbp0(it.raw)}  ·  ${rows[it.dataIndex].n} listings` };
  o.scales.x.ticks.callback = v => gbpK(v);
  o.scales.y.ticks.font = { family:"IBM Plex Mono", size:11 };
  o.scales.y.afterFit = sc => { sc.width = Math.max(sc.width, 84); };
  const clip = s => s.length > 15 ? s.slice(0,14) + "…" : s;
  const labelPlugin = {
    id:"cnt"+elId,
    afterDatasetsDraw(ch){
      const {ctx} = ch; ctx.save();
      ctx.font = "10px 'IBM Plex Mono'"; ctx.fillStyle = p.muted; ctx.textBaseline = "middle";
      ch.getDatasetMeta(0).data.forEach((bar,i)=>{
        ctx.textAlign = "left";
        ctx.fillText(rows[i].n, bar.x + 6, bar.y);
      });
      ctx.restore();
    }
  };
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:rows.map(r=>clip(r.seg)),
    datasets:[{ data:rows.map(r=>r.median), backgroundColor:color, borderRadius:3,
      maxBarThickness:22 }] }, options:o, plugins:[labelPlugin] }));
}

function renderBeds(p){
  const el = $("#c-beds"); const rows = DATA.by_bedrooms || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(rows.length===0){ box(el,"No data."); return; }
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label==="Studio"?"Studio / 0-bed":it[0].label+" bed",
    label: it => `${gbp0(it.raw)} · ${rows[it.dataIndex].n} listings` };
  o.scales.y.ticks.callback = v => gbpK(v);
  const lp = { id:"bedcnt", afterDatasetsDraw(ch){
    const {ctx} = ch; ctx.save(); ctx.font = "10px 'IBM Plex Mono'"; ctx.fillStyle = p.muted;
    ctx.textAlign = "center";
    ch.getDatasetMeta(0).data.forEach((b,i)=>ctx.fillText(rows[i].n, b.x, b.y - 6));
    ctx.restore();
  }};
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:rows.map(r=>r.seg),
    datasets:[{ data:rows.map(r=>r.median), backgroundColor:p.accent, borderRadius:3, maxBarThickness:44 }] },
    options:o, plugins:[lp] }));
}

function renderDist(p){
  const el = $("#c-dist"); const d = DATA.price_distribution;
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!d || !d.counts.length){ box(el,"No data."); return; }
  const labels = d.edges.slice(0,-1).map(e => "£"+Math.round(e/1e3)+"k");
  const o = baseOpts(p);
  o.plugins.tooltip.callbacks = { title: it=>it[0].label+" – "+labels[it[0].dataIndex+1] || "",
    label: it => it.raw + " listings" };
  o.scales.x.ticks.autoSkip = true; o.scales.x.ticks.maxTicksLimit = 8;
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels, datasets:[
    { data:d.counts, backgroundColor:p.accent, borderRadius:2, barPercentage:1, categoryPercentage:.92 }
  ]}, options:o }));
}

function renderQual(p){
  const el = $("#c-qual"); const q = DATA.price_qualifier || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(q.length===0){ box(el,"No data."); return; }
  const total = q.reduce((a,b)=>a+b.n,0);
  const o = baseOpts(p);
  o.indexAxis = "y";
  o.plugins.tooltip.callbacks = { title: it=>q[it[0].dataIndex].seg,
    label: it => `${it.raw} listings  ·  ${(100*it.raw/total).toFixed(0)}%` };
  o.scales.y.ticks.font = { family:"IBM Plex Mono", size:11 };
  o.scales.y.afterFit = sc => { sc.width = Math.max(sc.width, 128); };
  const clip = s => s.length > 18 ? s.slice(0,17) + "…" : s;
  const colors = q.map(r => /offers over/i.test(r.seg) ? p.orange : p.accent);
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:q.map(r=>clip(r.seg)),
    datasets:[{ data:q.map(r=>r.n), backgroundColor:colors, borderRadius:3, maxBarThickness:22 }] },
    options:o }));
}

function isDarkTheme(){
  const t = document.documentElement.getAttribute("data-theme");
  if(t === "dark") return true;
  if(t === "light") return false;
  return window.matchMedia("(prefers-color-scheme: dark)").matches;
}

// Sequential single-hue scale (light -> dark blue) over the real price range -
// magnitude, so one hue, never a rainbow. Built from the data's own quantiles,
// shared by the rank chart and the trend chart so a district reads the same
// colour in both.
function priceColorScale(rows){
  const prices = rows.map(r => r.median).slice().sort((a,b) => a-b);
  const qAt = f => prices[Math.min(prices.length-1, Math.round(f*(prices.length-1)))];
  const steps = [qAt(0), qAt(.2), qAt(.4), qAt(.6), qAt(.8), qAt(1)];
  // Light mode: cheap=light blue -> dear=dark blue (dark pops on a light surface).
  // Dark mode: the same family, reversed - a dark step recedes into the dark
  // surface the way a light step recedes into a white one, so "further from the
  // surface = higher value" stays true in both.
  const rampLight = ["#cde2fb","#9ec5f4","#6da7ec","#3987e5","#1c5cab","#0d366b"];
  const ramp = isDarkTheme() ? rampLight.slice().reverse() : rampLight;
  return v => {
    for(let i=steps.length-1;i>=0;i--) if(v >= steps[i]) return ramp[Math.min(i, ramp.length-1)];
    return ramp[0];
  };
}

function renderAreaRank(p){
  const el = $("#c-area-rank"); const rows = DATA.by_area || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(rows.length===0){ box(el,"No area data in the latest snapshot."); return; }
  const cityMed = DATA.city_median;
  const priceColor = priceColorScale(rows);
  const o = baseOpts(p);
  o.indexAxis = "y";
  o.layout.padding.right = 34;
  o.plugins.tooltip.callbacks = {
    title: it => `${rows[it[0].dataIndex].seg} · ${rows[it[0].dataIndex].name}`,
    label: it => {
      const r = rows[it.dataIndex];
      const vs = (r.vs_city>=0?"+":"") + (100*r.vs_city).toFixed(0) + "% vs city";
      return [`${gbp0(r.median)}  (${vs})`, `${r.n} listings · ${r.pct_reduced.toFixed(0)}% reduced`];
    },
  };
  o.scales.x.ticks.callback = v => gbpK(v);
  o.scales.y.ticks.font = { family:"IBM Plex Mono", size:11 };
  o.scales.y.afterFit = sc => { sc.width = Math.max(sc.width, 46); };
  const cnt = { id:"arcnt", afterDatasetsDraw(ch){
    const {ctx} = ch; ctx.save();
    ctx.font = "10px 'IBM Plex Mono'"; ctx.fillStyle = p.muted; ctx.textBaseline = "middle"; ctx.textAlign = "left";
    ch.getDatasetMeta(0).data.forEach((b,i)=>ctx.fillText(rows[i].n, b.x + 6, b.y));
    ctx.restore();
  }};
  const refline = { id:"arref", afterDatasetsDraw(ch){
    if(cityMed==null) return;
    const x = ch.scales.x.getPixelForValue(cityMed);
    const {top,bottom} = ch.chartArea; const {ctx} = ch;
    ctx.save();
    ctx.strokeStyle = p.ink2; ctx.setLineDash([4,3]); ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(x,top); ctx.lineTo(x,bottom); ctx.stroke();
    ctx.setLineDash([]); ctx.fillStyle = p.ink2; ctx.font = "9px 'IBM Plex Mono'"; ctx.textAlign = "center";
    ctx.fillText("city median", x, top - 3);
    ctx.restore();
  }};
  CHARTS.push(new Chart(el, { type:"bar", data:{ labels:rows.map(r=>r.seg),
    datasets:[{ data:rows.map(r=>r.median), backgroundColor:rows.map(r=>priceColor(r.median)),
      borderRadius:3, maxBarThickness:20 }] },
    options:o, plugins:[cnt, refline] }));
}

function renderAreaTrendAll(p){
  const el = $("#c-area-trend"); const at = DATA.area_trend; const ranked = DATA.by_area || [];
  if(!el || el.tagName!=="CANVAS"){ return; }
  if(!at || at.series.length===0 || ranked.length===0){ box(el,"No area history yet."); return; }
  const priceColor = priceColorScale(ranked);
  const bySeg = {}; at.series.forEach(s => bySeg[s.seg] = s);
  const series = ranked.filter(r => bySeg[r.seg]).map(r => ({ r, s: bySeg[r.seg] }));
  const one = at.dates.length < 2;

  const o = baseOpts(p);
  o.layout.padding.right = 40;
  o.interaction = { mode:"nearest", intersect:true };
  o.plugins.tooltip.callbacks = {
    title: it => it[0].label,
    label: it => `${series[it.datasetIndex].r.name} (${it.dataset.label})  ${gbp0(it.raw)}`,
  };
  o.scales.x.ticks.maxTicksLimit = 10;
  o.scales.y.ticks.callback = v => gbpK(v);

  const endLabels = { id:"arlabels", afterDatasetsDraw(ch){
    const {ctx} = ch; ctx.save();
    ctx.font = "10px 'IBM Plex Mono'"; ctx.textBaseline = "middle"; ctx.textAlign = "left";
    const marks = ch.data.datasets.map((ds,i) => {
      const meta = ch.getDatasetMeta(i);
      const pts = meta.data.filter((pt,j) => ds.data[j] != null);
      if(pts.length===0) return null;
      const last = pts[pts.length-1];
      return { x:last.x, y:last.y, color:ds.borderColor, label:ds.label };
    }).filter(Boolean).sort((a,b) => a.y-b.y);
    // declutter: enforce a minimum vertical gap between neighbouring end-labels
    for(let i=1;i<marks.length;i++){
      if(marks[i].y - marks[i-1].y < 11) marks[i].y = marks[i-1].y + 11;
    }
    marks.forEach(m => { ctx.fillStyle = m.color; ctx.fillText(m.label, m.x + 6, m.y); });
    ctx.restore();
  }};

  CHARTS.push(new Chart(el, { type:"line", data:{ labels:at.dates,
    datasets: series.map(({r,s}) => ({
      label: r.seg, data: s.points, borderColor: priceColor(r.median),
      backgroundColor: priceColor(r.median), borderWidth: 1.75, tension:.2,
      pointRadius: one?3:0, pointHoverRadius:4, spanGaps:true,
    })) }, options:o, plugins:[endLabels] }));
}

function renderAreaTable(){
  const host = $("#area-table"); if(!host) return;
  const rows = DATA.by_area || [];
  if(rows.length===0){ host.innerHTML = "<tr><td>No area data yet.</td></tr>"; return; }
  const mv = {}; (DATA.area_movers || []).forEach(m => mv[m.seg] = m);
  const hasDelta = Object.keys(mv).length > 0;
  const head = `<thead><tr><th>Area</th><th>Listings</th><th>Median asking</th>
    <th>vs city</th><th>% reduced</th><th>Median days</th>${hasDelta?"<th>Δ since first</th>":""}</tr></thead>`;
  const body = rows.map(r => {
    const vs = 100*r.vs_city;
    const vsc = vs<0 ? "neg" : (vs>0 ? "pos" : "");
    const dom = r.median_dom==null ? "—" : Math.round(r.median_dom);
    let dcell = "";
    if(hasDelta){
      const m = mv[r.seg];
      if(m){ const dc = m.pct<0?"neg":(m.pct>0?"pos":"");
        dcell = `<td class="${dc}">${pct1(m.pct)}</td>`; }
      else dcell = "<td>—</td>";
    }
    return `<tr><td>${r.name} <span class="oc">${r.seg}</span></td>
      <td>${r.n}</td><td>${gbp0(r.median)}</td>
      <td class="${vsc}">${vs>0?"+":""}${vs.toFixed(0)}%</td>
      <td>${r.pct_reduced.toFixed(0)}%</td><td>${dom}</td>${dcell}</tr>`;
  }).join("");
  host.innerHTML = head + "<tbody>" + body + "</tbody>";
}

// Rightmove-sourced free text (address, branch name) - escape before innerHTML.
function esc(s){
  return String(s ?? "").replace(/[&<>"']/g, c => ({
    "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;",
  }[c]));
}

let LOFT_SORT = "score"; // "score" (payload's default order) or "new" (most recently listed first)

function sortedLoftRows(){
  const rows = (DATA.loft_candidates || []).slice();
  if(LOFT_SORT === "new"){
    rows.sort((a,b) => {
      const ta = a.first_visible_date ? new Date(a.first_visible_date).getTime() : 0;
      const tb = b.first_visible_date ? new Date(b.first_visible_date).getTime() : 0;
      return tb - ta || b.score - a.score;
    });
  }
  return rows;
}

function renderLoftGrid(){
  const host = $("#loft-grid"); if(!host) return;
  const all = DATA.loft_candidates || [];
  const btn = $("#loft-open-all");
  const seg = $("#loft-sort");
  const nEl = $("#loft-n");
  const deltaEl = $("#loft-delta");
  if(nEl) nEl.textContent = all.length;
  if(deltaEl){
    const nNew = DATA.loft_new_count || 0, nGone = DATA.loft_dropped_count || 0;
    const parts = [];
    if(nNew) parts.push(`<span class="delta-new">+${nNew} new</span>`);
    if(nGone) parts.push(`<span class="delta-gone">${nGone} no longer matching</span>`);
    deltaEl.innerHTML = parts.length ? ` · since yesterday: ${parts.join(", ")}` : "";
  }

  if(!DATA.loft_text_available){
    host.innerHTML = '<div class="empty" style="padding:26px 20px">' +
      "Today's snapshot predates the free-text scan being added — tomorrow's run will pick up descriptions " +
      "and key features, and this list will fill in.</div>";
    $("#loft-cs").style.display = "none";
    if(btn) btn.style.display = "none";
    if(seg) seg.style.display = "none";
    return;
  }
  if(all.length === 0){
    host.innerHTML = '<div class="empty" style="padding:26px 20px">' +
      "No strong industrial-loft matches in today's snapshot. That's normal — this stock turns over slowly. " +
      "Check back after the next daily run.</div>";
    if(btn) btn.style.display = "none";
    if(seg) seg.style.display = "none";
    return;
  }

  if(seg){
    seg.style.display = "";
    seg.querySelectorAll(".seg-btn").forEach(b => {
      b.classList.toggle("active", b.dataset.sort === LOFT_SORT);
      b.onclick = () => { LOFT_SORT = b.dataset.sort; renderLoftGrid(); };
    });
  }

  const rows = sortedLoftRows();
  host.innerHTML = rows.map(r => {
    const tier = r.score >= 6 ? "strong" : "maybe";
    const beds = r.bedrooms == null ? "" : `${r.bedrooms} bed`;
    const size = r.size_sqft ? `${r.size_sqft.toLocaleString("en-GB")} sq ft` : "";
    const meta = [beds, r.property_sub_type, size].filter(Boolean).join(" · ");
    const chips = r.matches.map(m => `<span class="loft-chip">${esc(m)}</span>`).join("");
    const added = r.added_or_reduced ? esc(r.added_or_reduced) : "";
    const newTag = r.is_new ? '<span class="loft-new-tag">NEW</span>' : "";
    return `<div class="loft-row${r.is_new ? " is-new" : ""}">
      ${newTag}
      <span class="loft-score ${tier}">${r.score}</span>
      <span class="loft-price">${gbp0(r.price)}</span>
      <span class="loft-qual">${esc(r.price_qualifier || "")}</span>
      <div class="loft-main">
        <div class="loft-addr" title="${esc(r.display_address || "")}">${esc(r.display_address || "")}</div>
        <div class="loft-meta">${esc(meta)}</div>
        <div class="loft-chips">${chips}</div>
      </div>
      <div class="loft-foot">
        ${added}${added && r.branch_name ? "<br>" : ""}${esc(r.branch_name || "")}
        ${r.property_url ? `<br><a href="${esc(r.property_url)}" target="_blank" rel="noopener">View ↗</a>` : ""}
      </div>
    </div>`;
  }).join("");

  if(btn){
    btn.style.display = "";
    btn.onclick = () => {
      const urls = all.map(r => r.property_url).filter(Boolean);
      urls.forEach(u => window.open(u, "_blank", "noopener"));
    };
  }
}

function box(canvas, msg){
  const d = document.createElement("div");
  d.className = "empty"; d.textContent = msg;
  canvas.replaceWith(d);
}

function kpis(){
  const s = DATA.snapshot, h = DATA.ukhpi, f = DATA.forecast;
  const cells = [];
  if(s){
    cells.push(["Live listings", s.n_listings.toLocaleString("en-GB"), `${s.n_new_7d} new in 7 days`]);
    cells.push(["Median asking", gbp0(s.median_price), `IQR ${gbpK(s.p25_price)}–${gbpK(s.p75_price)}`]);
    cells.push(["Showing a price cut", s.pct_reduced.toFixed(0)+"%",
      `${Math.round(s.pct_reduced*s.n_listings/100)} of ${s.n_listings.toLocaleString("en-GB")}`]);
  }
  if(h){
    cells.push(["UK HPI avg price", gbp0(h.avg_price), `to ${h.latest_month}`]);
    cells.push(["HPI annual change", pct1(h.annual_change_pct),
      {t:"year to "+h.latest_month, c: h.annual_change_pct>=0?"up":"down"}]);
  }
  if(f){
    cells.push(["Forecast, 12 months", gbp0(f.projected_price),
      {t:pct1(f.projected_change_pct)+" vs now", c: f.projected_change_pct>=0?"up":"down"}]);
  }
  $("#kpis").innerHTML = cells.map(([k,v,d])=>{
    const dd = typeof d === "object" ? `<div class="d ${d.c}">${d.t}</div>` : `<div class="d">${d||""}</div>`;
    return `<div class="kpi"><div class="k">${k}</div><div class="v">${v}</div>${dd}</div>`;
  }).join("");
}

function renderAll(){
  destroyAll();
  const p = palette();
  kpis();
  renderForecast(p);
  renderAreaRank(p);
  renderAreaTrendAll(p);
  renderAreaTable();
  renderLoftGrid();
  renderAsking(p);
  renderInventory(p);
  hbar("c-type", DATA.by_type, p, p.aqua);
  renderBeds(p);
  renderDist(p);
  renderQual(p);
}

$("#gen").textContent = DATA.generated_at;
$("#loc").textContent = DATA.location;
$("#nsnap").textContent = DATA.n_snapshots || 1;
if((DATA.n_snapshots||1) < 2){
  $("#ts-note").textContent =
    "Only one snapshot so far — these two panels become trend lines once the daily task has run for a week or two.";
}
// Render once fonts are ready so Chart.js measures label widths with the real
// face (otherwise IBM Plex Mono swaps in after layout and axis labels clip).
if(document.fonts && document.fonts.ready){
  document.fonts.ready.then(renderAll);
  setTimeout(() => { if(CHARTS.length===0) renderAll(); }, 1200);
} else {
  renderAll();
}
window.matchMedia("(prefers-color-scheme:dark)").addEventListener("change", renderAll);
new MutationObserver(renderAll).observe(document.documentElement, { attributes:true, attributeFilter:["data-theme"] });
</script>
"""
